wavesplatform/gowaves

pkg/consensus/blocks_validation.go
pkg/libs/serializer/serializer.go

Wraps a few constants with correct signed-ness and bitwidth.
These otherwise result  in errors when compiling on 32 bit systems.

Two small patches to let gowaves build on 32 bit systems

---

pkg/consensus/blocks_validation.go
pkg/libs/serializer/serializer.go

* specify uint64 for constants
* tag uint32s for 32 bit builds
* camelCase for variables

Two small patches to let gowaves build on 32 bit systems (#533)

---

pkg/state/assets.go
pkg/state/assets_test.go
pkg/state/transaction_performer.go

Now 'assets.newestChangeableInfo' and 'assets.updateAssetInfo' methods accept 'crypto.Digest' instead of 'proto.AssetID'.

Newest asset info fix

---

cmd/retransmitter/retransmit/behaviour_test.go
cmd/retransmitter/retransmit/transaction_list_test.go
pkg/grpc/server/common_test.go
pkg/miner/internal_test.go
pkg/miner/miner_test.go
pkg/proto/addresses_test.go
pkg/proto/microblock_test.go
pkg/proto/transactions_test.go
pkg/proto/types_test.go
pkg/ride/converters_test.go
pkg/ride/tree_evaluation_test.go
pkg/ride/vm_test.go
pkg/state/block_differ_test.go
pkg/state/ethereum_tx_test.go
pkg/state/transaction_differ_test.go
pkg/state/verifier_test.go
pkg/wallet/embedded_wallet_test.go

As suggested in issue #270, I've changed many of MainNetScheme to TestNetScheme, most of the ones that just needed changing without any additional refactoring in a way that it doesn't break tests.
```
find . -type f -name "*_test.go"  | xargs grep "MainNet" |  wc -l
943
git checkout tests-testnet 
find . -type f -name "*_test.go"  | xargs grep "MainNet" |  wc -l
261
```
```
find . -type f -name "*_test.go"  | xargs grep "MainNetScheme" |  wc -l
145
git checkout master
find . -type f -name "*_test.go"  | xargs grep "MainNetScheme" |  wc -l
821
```

Mainnet -> testnet in tests

---

pkg/state/appender.go

Activate error behaviour in 'txAppender.checkScriptsLimits' method
after 'RideV6' feature activation.

Fix 'TODO' with block error complexity excess.

---

pkg/grpc/server/accounts_api_test.go
pkg/grpc/server/assets_api_test.go
pkg/grpc/server/blockchain_api_test.go
pkg/grpc/server/blocks_api_test.go
pkg/grpc/server/common_test.go
pkg/grpc/server/transactions_api_test.go
pkg/grpc/server/tx_filter_leases_test.go
pkg/keyvalue/bloom_filter_test.go
pkg/keyvalue/leveldb_test.go
pkg/node/peer_manager/storage/cbor_test.go
pkg/state/address_transactions_test.go
pkg/state/headers_validation_test.go
pkg/state/invoke_applier_test.go
pkg/state/state_test.go

A testing cleanup. 
This pull request replaces `ioutil.TempDir` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
This saves us at least 2 lines (error check, and cleanup) on every instance, or in some cases adds cleanup that we forgot.
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := ioutil.TempDir("", "")
require.NoError(t, err)
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
```

test: use `T.TempDir` to create temporary test directory

---

pkg/client/addresses.go
pkg/client/addresses_test.go

New API endpoints in client (with tests):
/addresses/data/{address} (GET - AddressesData)
/addresses/data/{address}/{key} (GET- AddressesDataKey)
/addresses/data/{address} (POST - AddressesDataKeys)

Client data endpoints with tests

---

itests/config/config.go
pkg/api/app_peers.go
pkg/api/app_peers_test.go
pkg/api/node_api.go
pkg/api/routes.go
pkg/mock/peer_manager.go
pkg/mock/peer_storage.go
pkg/node/peer_manager/peer_manager.go
pkg/node/peer_manager/peer_storage.go
pkg/node/peer_manager/peer_storage_test.go
pkg/node/peer_manager/storage/cbor.go
pkg/node/peer_manager/storage/cbor_test.go
pkg/node/peer_manager/storage/types.go
pkg/node/peer_manager/storage/types_test.go
pkg/node/state_fsm/fsm_common.go
pkg/node/state_fsm/fsm_idle.go
pkg/node/state_fsm/fsm_ng.go
pkg/node/state_fsm/fsm_sync.go
pkg/util/common/util.go
pkg/util/common/util_test.go

Now, node prevents establishing outgoing connections with peers in`suspended` list and incoming connections with peers in `blackList` as it works in scala node.

Add blacklisting

---

pkg/crypto/crypto.go
pkg/crypto/crypto_test.go

Need for [wavesplatform/nodemon/issues/92](https://github.com/wavesplatform/nodemon/issues/92).

Add hex string representation for 'crypto.Digest'.

---

pkg/ride/functions_invocations.go
pkg/ride/functions_proto.go
pkg/ride/tree_evaluation_test.go

Also accessing to `payment` field of `rideInvocation` removed because this field doesn't exist in Ride`Invocation` structure  since RideV5.
This PR is followed up by #935 where Ride structures of different versions will be represented.

move callee dapp version check in invoke() to the beginning

---

cmd/node/node.go
pkg/client/peers.go

Do not generate random nonce more than MaxInt32.

Handle negative peer nonce in API client correctly.

---

itests/fixtures/base_fixtures.go
itests/net/connection.go
itests/utilities/common_tx_utility.go

Function that creates new connections do it with retry. Network connections to nodes created only to send a transaction.

Network connections removed from suite fields.

---

pkg/state/block_differ_test.go
pkg/state/rewards_calculator.go
pkg/state/rewards_calculator_test.go

Fixed behavior of 'rewardCalculator' when features 19 and 21 are activated without feature 20.
Share only 1/3 of reward for each reward address.

Reward calculator feature 19 and 21 fix

---

pkg/state/snapshot_applier.go
pkg/state/snapshot_generator.go
pkg/state/snapshot_generator_internal_test.go
pkg/state/transaction_performer.go
pkg/state/tx_snapshot.go

Due to compatibility with old statehashes we have to set an empty script for any new non-scripted asset.

Set empty script for non-scripted assets.

---

pkg/api/metamask/service.go
pkg/proto/eth_transaction.go
pkg/proto/eth_tx_kind_resolver.go
pkg/ride/functions_proto.go

Now function returns transaction only if transfer is regular or ethereum transfer transaction. Otherwise it returns 'unit'.

Fix 'transferTransactionById' in Ride.

---

pkg/state/appender.go

According to the scala node [code](https://github.com/wavesplatform/Waves/blob/version-1.5.x/node/src/main/scala/com/wavesplatform/state/diffs/BlockDiffer.scala#L318-L323).
Continuation of #1269

Return previous snapshot state hash if init snapshot is empty.

---

pkg/miner/micro_miner.go
pkg/state/appender.go

Adding block height reduced by 1 for UTX transactions validation.

---

Dockerfile.gowaves-it

Bumps golang from 1.21.7-alpine3.18 to 1.22.0-alpine3.19.

Bump golang from 1.21.7-alpine3.18 to 1.22.0-alpine3.19

---

pkg/proto/microblock.go
pkg/proto/microblock_test.go

Handle new 'StateHash' field for 'MicroBlock' signature.

---

pkg/proto/protobuf_converters.go
pkg/proto/types_test.go

Use 'MarshalVTStrict' method for determenistic protobuf marshaling in 'MarshalToProtobufDeterministic' function.

Fix 'EthereumOrderV4.BodyMarshalBinary' protobuf marshaling order

---

pkg/state/appender.go
pkg/state/snapshot_applier.go
pkg/state/snapshot_generator_internal_test.go
pkg/state/tx_snapshot.go

This commit changes the 'extendedSnapshotApplier' interface. Now 'SetApplierInfo' method returns the 'cleanup' closure, which should be called in order to do some cleaning jobs.
Current implementation cleans zero state hash records which have zero diffs.
Cleanup has been also added for `txAppender.validateNextTx` method.

Add 'cleanup' func for snapshot applier.

---

pkg/state/rewards_calculator.go
pkg/state/rewards_calculator_test.go

Now the calculator only depends on passed parametes and does not depend on the features activation state on the blockchain current height. Though the calculator needs info about node features activation statutes at the passed height.

Fix block rewards calculator.

---

pkg/crypto/merkle.go
pkg/crypto/merkle_test.go
pkg/ride/functions_proto.go
pkg/ride/functions_proto_test.go

Now `rebuildMerkleRoot` go function accepts proofs in from-leafs-to-root order which is correct.

Fix 'createMerkleRoot' ride function.

---

pkg/ride/complexity.go
pkg/ride/complexity_test.go
pkg/ride/fold_evaluation_test.go
pkg/ride/functions_proto_test.go
pkg/ride/ride_constructors_test.go
pkg/ride/test_helpers_test.go
pkg/ride/tree_evaluation_test.go
pkg/ride/tree_evaluator.go

This PR is intended to prevent bugs with zero native functions complexity since `RideV6` feature activation (similar bug #1448).

Refactor ride complexity calculator

---

pkg/grpc/server/accounts_api.go
pkg/grpc/server/assets_api.go
pkg/grpc/server/blockchain_api.go
pkg/grpc/server/blocks_api.go
pkg/grpc/server/transactions_api.go
pkg/ride/compiler/ast_parser.go
pkg/ride/errors.go
pkg/state/state.go

This PR also fixes some `golangci-lint` issues.

Add log record about rollback action.

---

.github/workflows/go.yml
.golangci-strict.yml

Golangci-lint version updated to v1.60.2.

Deprecated linter "exportloopref" replaced with "copyloopvar".

---

Dockerfile.gowaves-it
itests/docker/docker.go

See https://github.com/moby/moby/issues/48274.
Network and FSM logging turned on for Gowaves node during integration tests.

Added work-around to handle the Docker configuration issue

---

pkg/state/appender.go
pkg/state/state.go

Fixed 'AddDeserializedBlocks' error miss.

Removed reusing error variables in 'stateManager'.

---

.github/workflows/security.yml

Fixes issues with SARIF result uploads.

Use 'securego/gosec@d4617f5' action.

---

pkg/consensus/blocks_validation.go
pkg/consensus/validator_moq_test.go
pkg/state/balances.go
pkg/state/balances_test.go
pkg/state/constants.go
pkg/state/history_storage.go
pkg/state/keys.go
pkg/state/state.go
pkg/state/state_test.go

This PR **breaks compatibility** with the previous state version.
Fix for #1423.
The challenger’s bonus is now only considered during block header validation. The effective balance of the challenged is now reset at the block height with the "challenge".

Fix challenged blocks handling.

---

itests/utilities/common.go
itests/utilities/issue/issue.go
itests/utilities/transfer/transfer.go

Adding an error in case of a problem with the issue of assets, adding additional checks in transfer methods.

Adding an error occurrence in case of a problem with the issue of assets and checks in transfer methods.

---

cmd/importer/importer.go

Return error instead of killing process with fatal log record.

Handle blockchain import errors properly

---

pkg/state/transaction_checker.go

Because err has been checked before and return as != nil.
Err here must be nil, and `errCF` should actually be return.

fix: fix incorrect nil return value

---

itests/burn_tx_api_internal_test.go
itests/burn_tx_internal_test.go
itests/reissue_tx_api_internal_test.go
itests/reissuie_tx_internal_test.go
itests/smoke_tx_api_positive_internal_test.go
itests/smoke_tx_positive_internal_test.go
itests/testdata/update_asset_info_testdata.go
itests/transfer_tx_api_internal_test.go
itests/transfer_tx_internal_test.go
pkg/ride/compiler/compaction.go

Since Go 1.21, the functions in x/exp used here can already be replaced by functions from the standard library.

refactor: replace golang.org/x/exp with stdlib

---

pkg/node/peers/score_selector.go

For more info see https://go.dev/issue/61716.

Replace deprecated 'golang.org/x/exp/rand' to 'math/rand/v2'

---

.github/workflows/security.yml

Excluded because rules in this ruleset contain 'security-severity' field with a string type value, while SARIF format accepts only numerical. For more info see https://github.com/semgrep/semgrep/issues/10834.

Exclude 'gitlab.gosec' ruleset from semgrep CI job.

---

pkg/proto/addresses.go

This pull request focuses on improving the robustness of the `Recipient` struct in the `pkg/proto/addresses.go` file by adding nil checks to various methods. These changes ensure that the methods handle cases where the `inner` field of `Recipient` is nil, preventing potential runtime errors.
Key changes include:
* Added a new helper function `errNilRecipient` to return a standardized error message when the `Recipient.inner` is nil.
* Updated the `Alias`, `Address`, `BinarySize`, `Eq`, `EqAddr`, `EqAlias`, `ToProtobuf`, `Valid`, and `MarshalJSON` methods to return appropriate values or errors when `r.inner` is nil.
* Modified the `MarshalBinary` method to return an error if `r.inner` is nil.
* Updated the `Serialize` method to return an error if `r.inner` is nil.
* Modified the `String` …

Handle nil value for recipient.

---

pkg/node/peers/spawner.go
pkg/proto/eth_typed_data.go
pkg/ride/compiler/compaction.go
pkg/ride/compiler/stdlib/types.go
pkg/ride/functions_proto.go

There is a [new function](https://pkg.go.dev/slices@go1.21.0#Contains) added in the go1.21 standard library, which can make the code more concise and easy to read.

refactor: use slices.Contains to simplify code

---

docker-entrypoint.sh
pkg/node/node.go
pkg/proto/proto.go
pkg/proto/proto_test.go

This pull request introduces enhancements to address validation and logging in the `Node` and `TCPAddr` components, along with corresponding unit tests for the new functionality. The key changes include adding a new method to check if both IP and port are empty, improving logging messages, and setting a default host when resolving empty addresses.
* Added a new method `EmptyNoPort` in `TCPAddr` to check if both the IP address is unspecified and the port is 0. This complements the existing `Empty` method. (`pkg/proto/proto.go`, [pkg/proto/proto.go:R594-R603](diffhunk://#diff-9414ee6fc81d60fc74df47fe91c3f51c820bf236c091908007209a3583b174cdR594-R603))
* Updated the `resolveHostToIPsv4` function to set the default host to `0.0.0.0` if the provided host is empty. (`pkg/proto/proto.go`, …

Fix empty bind address with enhancements in entrypoint.sh

---

.github/workflows/security.yml

Add sonatype credentials. For more info
see https://ossindex.sonatype.org/doc/auth-required. Briefly:
- All Sonatype OSS Index web and API access now requires authentication.
- Anonymous requests are no longer allowed.

Fix 'Nancy' step of 'Security' workflow.

---

itests/config/config.go
pkg/ride/compiler/ast_parser.go
pkg/ride/compiler/stdlib/types.go

strings.Builder has fewer memory allocations and better performance.
More info: [golang/go#75190](https://github.com/golang/go/issues/75190)  
Inspired by https://github.com/helm/helm/pull/31292/files

refactor: use strings.Builder to improve performance
