pkg/proto/address.go, pkg/proto/block.go, pkg/proto/block_test.go, pkg/proto/transactions.go, pkg/proto/transactions_test.go
Alias support added to Transfer, MassTransfer and Leasing transactions.
Transactions marshaling bugs fixed.
=> Block unmarshals transactions regarding the version.

pkg/db/db.go, pkg/server/server.go
Let's store per-height blocks history
```
$ curl 127.0.0.1:8080/blocks/at/height/391337 | pjson 
[
"3ecQGCpEC9jExUWX6Hndder6PptuTq6puTWHTMbou6ss9tmVDKZH2cKNSbHEqdngJQLCoGh3YCha9Hjspp6ooCM1"
]
```
```
$ curl 127.0.0.1:8080/blocks/at/height/391336 | pjson 
[
"649p8PnZqqgPtQMLNko1xSyrfuBwKFL43P9KdZsuSZy2ptLN5cRXWdaNdPd8hhaEFu8ZgatNNUd9M8PBJT8udoDJ", 
"44aoVEdp6p9PtKBJ8UZLjTj4wTxq7U181MiQLeSP51AwSHWQNHo4MzXhZPTxTibZwXpv1Yr1w6F5eN7yNXYSXjux"
]
```
```
$ curl 127.0.0.1:8080/blocks/at/height/391335 | pjson 
[
"5E22B8e6TrkfncJFkU8Q2bX6u3LzBCmqvykPzUL4K4NdmcWQmVhbUrEPSjT6tMiS1bPpfwMYwSpKQDeEHvPBySCj"
]
```
=> adds storing blocks for each height

cmd/wmd/internal/api.go, cmd/wmd/internal/data/symbols.go, cmd/wmd/internal/synchronizer.go, cmd/wmd/wmd.go, pkg/client/grpc/converters.go, pkg/client/grpc/grpc_test.go, pkg/importer/importer.go, pkg/proto/transactions.go, pkg/proto/transactionsv1.go, pkg/proto/transactionsv2.go, pkg/proto/types.go
…tion to convert DataEntry from gRPC. Linter errors fixed.
=> GO-187: Updating of tickers from TokenRating oracle implemented

cmd/wmd/internal/data/trade.go, cmd/wmd/internal/data/updates.go, pkg/proto/protobuf_converters.go, pkg/proto/transactions.go, pkg/proto/transactions_test.go, pkg/proto/transactions_with_proofs.go, pkg/proto/transactions_with_sig.go, pkg/ride/evaluator/ast/transactions.go, pkg/state/appender.go, pkg/state/transaction_checker.go, pkg/state/transaction_checker_test.go, pkg/state/transaction_differ.go, pkg/state/transaction_differ_test.go, pkg/state/transaction_performer.go, pkg/state/transaction_performer_test.go, pkg/state/verifier.go
=> Exchange orders any order

pkg/client/addresses.go
Saw this when I was looking around the code and saw that there was already an issue (#281) for it.
=> Update extra_fee to extraFee - closes #281

pkg/client/addresses.go
Co-authored-by: Shane Lee <me@shanel.ee>
=> Update extra_fee to extraFee - closes #281 (#283)

pkg/ride/evaluator/ast/functions.go, pkg/ride/evaluator/ast/functions_test.go, pkg/ride/evaluator/ast/scope.go, pkg/ride/evaluator/ast/transactions.go, pkg/ride/evaluator/evaluate/evaluate_test.go, pkg/ride/mockstate/mockstate.go, pkg/state/script_caller.go, pkg/state/scripts_storage.go, pkg/state/state.go, pkg/types/types.go
=> New function to get FullAssetInfo implemented for RIDE v4

pkg/state/fee_validation.go, pkg/state/fee_validation_test.go, pkg/state/test_util.go, pkg/state/transaction_checker_test.go, pkg/state/transaction_differ_test.go, pkg/state/transaction_performer_test.go
=> Fee for sponsorship transaction reduced to 1 fee unit after BlockV5 activation

pkg/ride/evaluator/ast/functions.go, pkg/ride/evaluator/ast/functions_test.go, pkg/ride/evaluator/ast/scope.go
=> Simplified Issue

pkg/grpc/server/assets_api.go, pkg/mock/state.go, pkg/state/accounts_data_storage.go, pkg/state/accounts_data_storage_test.go, pkg/state/api.go, pkg/state/assets.go, pkg/state/balances.go, pkg/state/balances_test.go, pkg/state/common_test.go, pkg/state/keys.go, pkg/state/state.go, pkg/state/threadsafe_wrapper.go
=> Implement GetNFTList

pkg/api/node_api.go, pkg/state/errors.go
…response for non-existent block.
=> Node http API 'blocks/at/{height}' method bugfix.

pkg/errs/tx_validation_errors.go, pkg/errs/tx_validation_errors_test.go
=> Is method implemented for custom errors.

pkg/state/address_transactions.go, pkg/state/batched_storage.go, pkg/state/constants.go, pkg/state/history_storage.go, pkg/state/history_storage_test.go, pkg/state/internal_constants.go, pkg/state/keys.go
Fixed incorrect initial value for storage keys enumeration.
Storage version incresed.
Tests on history records sizes added.
=> Fixed issue with incorrect keys during batched storage normalization.

pkg/ride/functions_proto.go, pkg/ride/functions_proto_test.go
=> Fixed support of Alias in addressFromRecipient ride function. Tests added.

pkg/proto/scripting.go, pkg/proto/types.go, pkg/ride/environment.go, pkg/ride/tree_evaluation_test.go
=> add limit on number of attached payments in sequental invokes by 100

pkg/proto/actions_validator.go, pkg/proto/scripting_test.go, pkg/ride/tree_evaluation_test.go
This reverts commit 3eb62146ea6ea7e70cf30c3c609ada60eb5fb8c1.
=> Revert "forbid zero payments in invokes (#754)"

pkg/client/addresses.go, pkg/client/addresses_test.go
=> Client '/addresses/data/' endpoints with tests

pkg/state/accounts_data_storage_test.go, pkg/state/address_transactions_test.go, pkg/state/aliases_test.go, pkg/state/assets_test.go, pkg/state/balances_test.go, pkg/state/batched_storage_test.go, pkg/state/block_differ_test.go, pkg/state/blockreadwriter_test.go, pkg/state/common_test.go, pkg/state/database_test.go, pkg/state/diff_applier_test.go, pkg/state/ethereum_tx_test.go, pkg/state/features_test.go, pkg/state/fee_validation_test.go, pkg/state/history_formatter_test.go, pkg/state/history_storage_test.go, pkg/state/invoke_results_test.go, pkg/state/leases_test.go, pkg/state/monetary_policy_test.go, pkg/state/orders_volume_test.go, pkg/state/scripts_complexity_test.go, pkg/state/scripts_storage_test.go, pkg/state/sponsored_assets_test.go, pkg/state/transaction_checker_test.go, pkg/state/transaction_differ_test.go, pkg/state/transaction_performer_test.go, pkg/util/common/util.go
Refactor 'createStorageObjects' function in 'pkg/state/common_test.go'.
=> State tests refactoring.

pkg/state/constants.go, pkg/state/database.go, pkg/state/state.go, pkg/state/state_test.go, pkg/state/transaction_checker.go, pkg/state/transaction_checker_test.go
These changes allow to use importer utility on state which has been used by node.
=> Store amend flag in state info.

pkg/state/state.go
=> Remove unnecessary err check in 'stateManager.addBlocks'.

pkg/api/app.go, pkg/api/node_api.go, pkg/api/routes.go
Wrapping of body reader in LimitReader added.
Returning of broadcasted transaciton added as API required.
Closes #888
=> Unnecessary authorization by api-key removed from broadcast method.

pkg/ride/converters.go, pkg/ride/converters_test.go, pkg/ride/environment.go, pkg/ride/functions_proto.go, pkg/ride/runtime.go, pkg/ride/runtime_moq_test.go, pkg/ride/runtime_test.go, pkg/ride/test_helpers_test.go, pkg/ride/tree_evaluation_test.go, pkg/ride/vm_test.go, pkg/state/appender.go, pkg/state/invoke_applier.go, pkg/state/script_caller.go
=> Fix 'setScriptWithProofsToObject' function.

pkg/mock/state.go, pkg/proto/types.go, pkg/state/api.go, pkg/state/constants.go, pkg/state/scripts_storage.go, pkg/state/scripts_storage_interface.go, pkg/state/scripts_storage_moq_test.go, pkg/state/state.go, pkg/state/threadsafe_wrapper.go, pkg/state/transaction_checker_test.go, pkg/state/transaction_differ_test.go, pkg/state/transaction_performer_test.go
These changes are incompatible with previous state version. State should be re-imported.
=> Scripts storage improvements

.github/workflows/security.yml, go.mod, go.sum
Now 'nancy' dependencies scanner checks only those dependencies which end up in the final binary.
=> Security CI workflow fix.

pkg/api/app_blocks.go, pkg/api/node_api.go, pkg/api/routes.go
Need for [wavesplatform/nodemon/issues/98](https://github.com/wavesplatform/nodemon/issues/98)
=> HTTP API '/blocks/headers/' endpoints

go.mod, go.sum, pkg/crypto/ecdsa.go, pkg/crypto/ecdsa_test.go, pkg/proto/eth_crypto.go, pkg/proto/eth_signer.go, pkg/proto/types.go, pkg/ride/converters_test.go, pkg/state/common_test.go
Also replacing 'github.com/btcsuite/btcd' dependency.
=> Migrate to 'github.com/btcsuite/btcd/btcec/v2'.

pkg/client/transactions_info_test.go, pkg/proto/types.go
Add 'array' case for switch in 'guessArgumentType' function.
=> Fixed 'Arguments.UnmarshalJSON' method.

Makefile, pkg/miner/scheduler/scheduler.go
Increased the timeout for integration tests.
=> Fixed the way how blockchain lag is calculated in miner.

itests/testdata/alias_tx_testdata.go, itests/testdata/burn_tx_testdata.go, itests/testdata/issue_tx_testdata.go, itests/testdata/reissue_tx_testdata.go
Testdata for negative tests was fixed.
=> Fix testdata for negative tests

itests/fixtures/base_fixtures.go, itests/node_client/http_client.go, itests/node_client/node_client.go
FIx waiting for peers connection
=> Wait for peers connection.

itests/fixtures/base_fixtures.go, itests/node_client/node_client.go, itests/utilities/transfer_utilities/transfer_tx_utility.go
=> Fix waiting for balances.

Dockerfile.gowaves-it, itests/node_client/http_client.go, itests/node_client/node_client.go, itests/utilities/common_tx_utility.go
Removed functions to clear blacklisted peers.
=> Switched off blacklisting on gowaves node.

itests/testdata/transfer_tx_testdata.go, itests/transfer_tx_api_test.go, itests/transfer_tx_test.go
Changing timestamp in test data for positive cases.
=> Changing timestamp in test data for positive cases.

pkg/proto/common.go, pkg/proto/transactions.go, pkg/proto/transactions_with_proofs.go, pkg/proto/types.go
Comments fixed.
Unused function removed.
=> Added size check on marshaling of byte slice with size.

pkg/ride/environment.go, pkg/ride/functions_bytes_test.go, pkg/ride/functions_proto_test.go, pkg/ride/test_helpers_test.go, pkg/ride/vm_test.go
Check fucntions implemented as separate functions in evironment.go and used in tests. Old test check functions removed.
=> Fixed check function for scripts version before V3.

itests/testdata/alias_tx_testdata.go, itests/testdata/burn_tx_testdata.go, itests/testdata/issue_smart_asset_tx_testdata.go, itests/testdata/issue_tx_testdata.go, itests/testdata/reissue_tx_testdata.go, itests/testdata/set_asset_script_tx_testdata.go, itests/testdata/sponsorship_testdata.go, itests/testdata/transfer_tx_testdata.go, itests/testdata/transfer_with_sponsorship_testdata.go, itests/utilities/alias_utilities/alias_tx_utility.go, itests/utilities/burn_utilities/burn_tx_utility.go, itests/utilities/common_tx_utility.go, itests/utilities/issue_utilities/issue_tx_utility.go, itests/utilities/reissue_utilities/reissue_tx_utility.go, itests/utilities/set_asset_script_utilities/set_asset_script_utility.go, itests/utilities/sponsor_utilities/sponsor_tx_utility.go, itests/utilities/transfer_utilities/transfer_tx_utility.go
Fix pointers in test data and utility methods
=> Fix pointers in test data and utility methods

itests/fixtures/base_fixtures.go, itests/node_client/node_client.go
Fix teardown method for test suites
=> Fix error with state hash cmp

itests/node_client/node_client.go
Fix WaitForStateHashEquality method
=> Fix WaitForStateHashEquality method

pkg/state/appender.go, pkg/state/fee_validation_test.go, pkg/state/invoke_applier.go, pkg/state/transaction_performer.go, pkg/state/transaction_performer_test.go
=> Initialized 'applicationResult.checkerData' for invoke transactions.

.github/workflows/go.yml, .golangci.yml
=> Increase linter timeout ci

cmd/blockcmp/blockcmp.go, cmd/importer/importer.go, cmd/rollback/main.go, cmd/statecmp/statecmp.go, cmd/wmd/wmd.go, pkg/logging/logger.go
Added deffered functions to sync logger on exit.
=> Fixed function for setting up simple logger configuration.

pkg/api/metamask/service.go, pkg/grpc/server/accounts_api.go, pkg/grpc/server/server_common.go, pkg/grpc/server/transactions_api.go, pkg/grpc/server/transactions_api_test.go, pkg/mock/state.go, pkg/proto/types.go, pkg/state/address_transactions.go, pkg/state/address_transactions_test.go, pkg/state/api.go, pkg/state/blockreadwriter.go, pkg/state/blockreadwriter_test.go, pkg/state/common_test.go, pkg/state/constants.go, pkg/state/snapshot_applier.go, pkg/state/state.go, pkg/state/threadsafe_wrapper.go, pkg/state/transaction_performer_test.go, pkg/types/types.go, pkg/util/iterators/tx_by_id.go, pkg/util/iterators/tx_by_id_test.go
This PR **breaks compatibility** with the previous state version.
=>  Handle 'elided' transaction status

pkg/proto/microblock.go, pkg/proto/protobuf_converters.go
=> Add new 'StateHash' field for 'MicroBlock'.

pkg/state/verifier.go, pkg/state/verifier_test.go
Continuation of #1302
According to [this](https://github.com/wavesplatform/Waves/blob/version-1.5.x/node/src/main/scala/com/wavesplatform/state/appender/package.scala#L215-L218)
=> Deny self-challenged blocks

.github/workflows/go.yml
Bumps golangci/golangci-lint-action from v2 to v3.
=> Bump golangci/golangci-lint-action from v2 to v3

pkg/state/assets.go, pkg/state/assets_test.go, pkg/state/balances.go, pkg/state/balances_test.go, pkg/state/common_test.go, pkg/state/constants.go, pkg/state/ethereum_tx_test.go, pkg/state/fee_validation.go, pkg/state/invoke_applier.go, pkg/state/snapshot_applier.go, pkg/state/snapshot_generator.go, pkg/state/snapshot_generator_internal_test.go, pkg/state/state.go, pkg/state/transaction_checker.go, pkg/state/transaction_checker_test.go, pkg/state/transaction_differ.go, pkg/state/transaction_performer_test.go
This PR **breaks compatibility** with the previous state version.
=> Fix 'isNFT' flag initialization for assets

pkg/proto/protobuf_converters.go, pkg/state/appender.go, pkg/state/balances.go, pkg/state/balances_test.go, pkg/state/constants.go, pkg/state/history_storage.go, pkg/state/keys.go, pkg/state/leases.go, pkg/state/leases_test.go, pkg/state/patches_storage.go, pkg/state/patches_storage_internal_test.go, pkg/state/snapshot_applier.go, pkg/state/state.go, pkg/state/tx_snapshot.go
This PR **breaks compatibility** with the previous state version.
=> Generate fix snapshots and apply them at initial snapshot stage

pkg/state/appender.go, pkg/state/snapshot_generator_internal_test.go, pkg/state/state.go
=> Fix light node fee distribution

itests/reward_distribution_info_internal_test.go, itests/utilities/assertions.go, itests/utilities/reward/reward.go
Change current height to height of feature 20 activation.
=> Fix height in itest for check term after Feature 20 activation.

pkg/state/snapshot_generator.go
Use ethereum transaction kind info for correct snapshot creation.
=> Fix 'snapshotGenerator.performEthereumTransactionWithProofs'

pkg/state/state.go
=> Fix patch generation and applying

pkg/settings/blockchain_settings.go, pkg/state/snapshot_generator.go, pkg/state/transaction_checker.go
Fix reissue flag in tx snapshof for special periods when non-reissuable assets can be reissued.
=> Fix snapshot generation for reissue tx.

pkg/ride/diff_state.go, pkg/ride/environment.go, pkg/ride/test_helpers_test.go, pkg/ride/tree_evaluation_test.go
According to the [scala node implementation](https://github.com/wavesplatform/Waves/blob/b3c874696f220598e1ab94b47f0135283964a32d/node/src/main/scala/com/wavesplatform/transaction/smart/WavesEnvironment.scala#L173-L176).
=> Update ride generating balance during tx after light node feature

itests/testdata/reward_distribution_rolllback_testdata.go
Fix rounding in reward test data.
=> Fix reward distribution itests

.github/workflows/deploy_node.yml
=> Deploy workflow fix

.github/workflows/deploy_node.yml, .github/workflows/deploy_nodes.yml
=> Fix deploy nodes reusable workflow 

cmd/node/node.go
=> Fix: print 'reward' flag value as int.

pkg/api/app.go, pkg/api/metamask/service.go, pkg/libs/ntptime/ntptime.go, pkg/node/fsm/tasks/tasks.go, pkg/node/node.go, pkg/util/limit_listener/listen.go
Ref: https://go.dev/wiki/Go123Timer
=> Prepare timers for go1.23.

Makefile
Target "build" added to build all native executables.
=> Targets to build native executables added where it was missed.

pkg/consensus/blocks_validation.go, pkg/proto/ethabi/methods_map.go, pkg/proto/ethabi/unpack.go, pkg/state/rewards_calculator.go, pkg/state/snapshot_hasher_internal_test.go, pkg/state/transaction_checker.go
=> chore: fix some comments

itests/init_internal_test.go
=> Fixed incorrect error usage in error message.

pkg/ride/compiler/ast_parser.go, pkg/ride/compiler/ast_parser_test.go
Test on escape sequences updated.
=> Lost escape sequence for back slash added to compiler.

.github/workflows/security.yml
=> Update semgrep job of security CI workflow.

cmd/binclient/main.go, cmd/blockcmp/blockcmp.go, cmd/chaincmp/README.md, cmd/genesis/genesis.go, itests/utilities/issue/issue.go
=> chore: fix some typos

pkg/state/api.go
=> chore: fix struct name in comment

pkg/proto/snapshot_types.go
Fix the wrong error return value
Inspired by https://github.com/wavesplatform/gowaves/pull/1617
=> fix: fix the wrong error return value

pkg/node/node.go
=> Close node's TCP listener by context cancellation

pkg/node/peers/storage/types.go, pkg/ride/crypto/rsa.go, pkg/ride/functions_bigint.go, pkg/ride/functions_strings.go
use the built-in max/min to simplify the code
=> refactor: use the built-in max/min to simplify the code

.github/workflows/security.yml
=> Fix 'security' workflow.
